server:
  port: 0

eureka:
  numberRegistrySyncRetries: 0
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5

---
spring:
  profiles: docker

server:
  port: 8090

hystrix.execution.isolation.strategy: SEMAPHORE

app:
  rabbitmq:
    host: rabbitmq
  graphite:
    host: graphite
    port : 2003

eureka:
  numberRegistrySyncRetries: 0
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eurekaService:8761/eureka/