info:
  component: zuul-service

server:
  port: 0

zuul:
  ignoredServices: "*"
  routes:
    catalog-service:
      path: /catalog-service/**

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

