server:
  port: 0

spring:
  sleuth:
    zuul:
      enabled: true
    log:
      json:
        enabled: true
zuul:
  routes:
    catalog-service:
      path: /catalog-service/**

    price-service:
      path: /price-service/**

    product-service:
      path: /product-service/**

    comment-service:
      path: /comment-service/**

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

hystrix:
  execution:
    isolation:
      strategy: SEMAPHORE

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

---
spring:
  sleuth:
    zuul:
      enabled: true
    log:
      json:
        enabled: true
  profiles: docker

hystrix:
  execution:
    isolation:
      strategy: SEMAPHORE

server:
  port: 8765

app:
  graphite:
    host: graphite
    port : 2003

eureka:
  numberRegistrySyncRetries: 0
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eurekaService:8761/eureka/

