spring:
  profiles: docker

server:
  port: 8761

app:
  graphite:
    host: graphite
    port : 2003

eureka:
  numberRegistrySyncRetries: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    ROOT: INFO


